name: goes_vintage_workflow
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - boto3
  - awscli
  - cdsapi
  - ipykernel
  - nbconvert
  - ipywidgets
  - numpy
  - pandas
  - matplotlib
  - imageio
  - xarray
  - rioxarray
  - gdal
  - pyproj
  - requests
  - rasterio
  - netcdf4
  - h5netcdf
  - zarr
  - dask
  - distributed
  - s3fs
  - fsspec
  - aiohttp
  - scipy
  - tqdm
  - pip
  - pip:
      - goes_ortho
      - git+https://github.com/palexandremello/goes-py.git
